(()=>{"use strict";
const KEY="dillo_dashboard_v5";
const seed={clients:[{id:1,name:"Mia Santos",company:"Bloom Wellness",email:"mia@bloomwellness.com",status:"Active"},{id:2,name:"Lucas Reed",company:"Northstar Finance",email:"lucas@northstarfinance.com",status:"Active"},{id:3,name:"Sofia Cruz",company:"Casa Migration",email:"sofia@casamigration.com",status:"Onboarding"},{id:4,name:"Eli Parker",company:"Good Energy Co.",email:"eli@goodenergy.co",status:"Paused"}],projects:[{id:11,name:"Bloom — September Content",client:"Bloom Wellness",status:"In progress",progress:72,due:"2026-09-24"},{id:12,name:"Northstar Brand Refresh",client:"Northstar Finance",status:"Review",progress:88,due:"2026-09-20"},{id:13,name:"Casa TikTok Launch",client:"Casa Migration",status:"In progress",progress:41,due:"2026-09-29"}],events:[{id:21,title:"Northstar review",date:"2026-09-20"},{id:22,title:"Bloom strategy call",date:"2026-09-22"},{id:23,title:"Bloom content due",date:"2026-09-24"},{id:24,title:"Casa launch",date:"2026-09-29"}],invoices:[{id:31,number:"INV-104",client:"Bloom Wellness",amount:650,status:"Paid"},{id:32,number:"INV-105",client:"Northstar Finance",amount:900,status:"Pending"},{id:33,number:"INV-106",client:"Casa Migration",amount:750,status:"Overdue"}],files:[{id:41,name:"Bloom Brand Kit.pdf",client:"Bloom Wellness",type:"PDF",size:"2.4 MB",status:"Approved"},{id:42,name:"Northstar Logo Pack.zip",client:"Northstar Finance",type:"ZIP",size:"8.1 MB",status:"Pending"},{id:43,name:"Casa Content Brief.docx",client:"Casa Migration",type:"DOCX",size:"0.8 MB",status:"Approved"}]};
let state=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(seed));
const page=document.getElementById("page"),title=document.getElementById("viewTitle"),back=document.getElementById("modalBackdrop"),content=document.getElementById("modalContent");
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const btn=(label,action,cls="primary")=>'<button class="btn '+cls+'" data-action="'+action+'">'+label+"</button>";
const del=(type,id)=>'<button class="small-btn danger-btn" data-remove="'+type+'" data-id="'+id+'">Delete</button>';
function shell(h,p,actions=""){return '<div class="hero"><div><div class="eyebrow">DILLO SOCIALS</div><h1>'+h+'</h1><p>'+p+'</p></div><div class="hero-actions">'+actions+"</div></div>"}
function card(h,b){return '<section class="panel"><div class="panel-head"><h2>'+h+'</h2></div><div class="panel-body">'+b+"</div></section>"}
function empty(t){return '<div class="empty">'+t+"</div>"}
function overview(){let active=state.clients.filter(c=>c.status==="Active").length,paid=state.invoices.filter(i=>i.status==="Paid").reduce((a,i)=>a+i.amount,0),out=state.invoices.filter(i=>i.status!=="Paid").reduce((a,i)=>a+i.amount,0);page.innerHTML=shell("Good morning, Dillo. <span>Let’s make things move.</span>","Your command center for clients, projects, calendar, invoices and files.",btn("+ New client","client")+btn("+ New project","project","secondary"))+'<div class="kpis"><div class="kpi"><div class="kpi-top">Active clients</div><strong>'+active+'</strong><small>'+state.clients.length+' total</small></div><div class="kpi"><div class="kpi-top">Projects</div><strong>'+state.projects.length+'</strong><small>Tracked in workspace</small></div><div class="kpi"><div class="kpi-top">Paid this cycle</div><strong>$'+paid.toLocaleString()+'</strong><small>Recorded payments</small></div><div class="kpi"><div class="kpi-top">Outstanding</div><strong>$'+out.toLocaleString()+'</strong><small>'+state.invoices.filter(i=>i.status!=="Paid").length+' open invoices</small></div></div><div class="overview-grid"><div class="overview-main">'+card("Needs your attention",(state.invoices.filter(i=>i.status==="Overdue").map(i=>'<div class="list-row"><div><b>'+esc(i.number)+' is overdue</b><small>'+esc(i.client)+' · $'+i.amount+'</small></div><span class="tag red">Action needed</span></div>').join("")+state.files.filter(f=>f.status==="Pending").map(f=>'<div class="list-row"><div><b>'+esc(f.name)+' needs approval</b><small>'+esc(f.client)+'</small></div><span class="tag yellow">Review</span></div>').join(""))||empty("Nothing needs your attention right now. ✦"))+card("Projects at a glance",state.projects.length?state.projects.map(p=>'<div class="list-row"><div><b>'+esc(p.name)+'</b><small>'+esc(p.client)+' · '+esc(p.status)+'</small></div><b>'+p.progress+'%</b></div>').join(""):empty("No projects yet."))+'</div><div class="overview-side">'+card("Quick actions",'<div class="quick-grid"><button class="quick" data-view="clients"><strong>Clients</strong><span>Manage relationships</span></button><button class="quick" data-view="projects"><strong>Projects</strong><span>Track work</span></button><button class="quick" data-view="calendar"><strong>Calendar</strong><span>Schedule work</span></button><button class="quick" data-view="invoices"><strong>Invoices</strong><span>Track billing</span></button><button class="quick" data-view="files"><strong>Files</strong><span>Client assets</span></button></div>')+card("Coming up",state.events.length?state.events.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(e=>'<div class="list-row"><div><b>'+esc(e.title)+'</b><small>'+esc(e.date)+'</small></div></div>').join(""):empty("Your calendar is empty."))+'</div></div>';bind()}
function clients(){let rows=state.clients.map(c=>'<tr><td><b>'+esc(c.name)+'</b><small>'+esc(c.email)+'</small></td><td>'+esc(c.company)+'</td><td>'+esc(c.status)+'</td><td><button class="small-btn" data-edit="client" data-id="'+c.id+'">Edit</button> '+del("client",c.id)+'</td></tr>').join("");page.innerHTML=shell("Clients.","Add, edit or remove your client records.",btn("+ Add client","client"))+card("Client list",rows?'<div style="overflow:auto"><table class="data-table"><thead><tr><th>Client</th><th>Business</th><th>Status</th><th></th></tr></thead><tbody>'+rows+"</tbody></table></div>":empty("No clients yet. Click “+ Add client”."));bind()}
function projects(){let rows=state.projects.map(p=>'<article class="project-card"><div class="project-top"><span class="tag blue">'+esc(p.status)+'</span><b>'+p.progress+'%</b></div><h3>'+esc(p.name)+'</h3><p>'+esc(p.client)+' · Due '+esc(p.due||"—")+'</p><div class="progress"><i style="width:'+p.progress+'%"></i></div><div style="margin-top:12px"><button class="small-btn" data-edit="project" data-id="'+p.id+'">Edit</button> '+del("project",p.id)+'</div></article>').join("");page.innerHTML=shell("Projects in motion.","Add, edit or remove projects and track progress.",btn("+ New project","project"))+'<div class="project-grid">'+(rows||empty("No projects yet. Click “+ New project”."))+"</div>";bind()}
function calendar(){let rows=state.events.map(e=>'<div class="list-row"><div><b>'+esc(e.title)+'</b><small>'+esc(e.date)+'</small></div><span><button class="small-btn" data-edit="event" data-id="'+e.id+'">Edit</button> '+del("event",e.id)+'</span></div>').join("");page.innerHTML=shell("Calendar.","Add, edit or remove calls, deadlines and launches.",btn("+ Add calendar item","event"))+card("Calendar",rows||empty("Your calendar is empty. Click “+ Add calendar item”."));bind()}
function invoices(){let rows=state.invoices.map(i=>'<tr><td><b>'+esc(i.number)+'</b></td><td>'+esc(i.client)+'</td><td>$'+i.amount+'</td><td>'+esc(i.status)+'</td><td><button class="small-btn" data-edit="invoice" data-id="'+i.id+'">Edit</button> '+del("invoice",i.id)+'</td></tr>').join("");page.innerHTML=shell("Invoices.","Add, edit or remove invoices and payment status.",btn("+ Add invoice","invoice"))+card("Invoice list",rows?'<div style="overflow:auto"><table class="data-table"><thead><tr><th>Invoice</th><th>Client</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>'+rows+"</tbody></table></div>":empty("No invoices yet. Click “+ Add invoice”."));bind()}
function files(){let rows=state.files.map(f=>'<div class="file-card"><span class="file-icon">'+esc(f.type)+'</span><div style="flex:1"><b>'+esc(f.name)+'</b><small>'+esc(f.client)+' · '+esc(f.size)+'</small></div><span class="tag '+(f.status==="Approved"?"green":"yellow")+'">'+esc(f.status)+'</span><button class="small-btn" data-edit="file" data-id="'+f.id+'">Edit</button> '+del("file",f.id)+'</div>').join("");page.innerHTML=shell("Files.","Add, edit or remove client assets and deliverables.",btn("+ Add file","file"))+card("Shared files",rows?'<div class="file-list">'+rows+"</div>":empty("No files yet. Click “+ Add file”."));bind()}
function modal(type,id){let item=id?state[type==="event"?"events":type+"s"].find(x=>x.id==id):null,cs=state.clients.map(c=>'<option value="'+esc(c.company)+'">'+esc(c.company)+'</option>').join("");let h={client:"Client",project:"Project",event:"Calendar item",invoice:"Invoice",file:"File"}[type],body="";
if(type==="client")body='<form data-type="client"><div class="form-grid"><div class="field"><label>Name</label><input name="name" required value="'+esc(item?.name)+'"></div><div class="field"><label>Business</label><input name="company" required value="'+esc(item?.company)+'"></div><div class="field"><label>Email</label><input name="email" type="email" value="'+esc(item?.email)+'"></div><div class="field"><label>Status</label><select name="status"><option>Active</option><option>Onboarding</option><option>Paused</option></select></div></div>'+actions(type)+'</form>';
if(type==="project")body='<form data-type="project"><div class="form-grid"><div class="field full"><label>Project name</label><input name="name" required value="'+esc(item?.name)+'"></div><div class="field"><label>Client</label><select name="client">'+cs+'</select></div><div class="field"><label>Due</label><input name="due" type="date" value="'+esc(item?.due)+'"></div><div class="field"><label>Status</label><select name="status"><option>Not started</option><option>In progress</option><option>Review</option><option>Complete</option></select></div><div class="field"><label>Progress %</label><input name="progress" type="number" min="0" max="100" value="'+(item?.progress??0)+'"></div></div>'+actions(type)+'</form>';
if(type==="event")body='<form data-type="event"><div class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" required value="'+esc(item?.date)+'"></div><div class="field"><label>Title</label><input name="title" required value="'+esc(item?.title)+'"></div></div>'+actions(type)+'</form>';
if(type==="invoice")body='<form data-type="invoice"><div class="form-grid"><div class="field"><label>Invoice #</label><input name="number" required value="'+esc(item?.number||"")+'"></div><div class="field"><label>Client</label><select name="client">'+cs+'</select></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0" required value="'+(item?.amount??0)+'"></div><div class="field"><label>Status</label><select name="status"><option>Pending</option><option>Paid</option><option>Overdue</option></select></div></div>'+actions(type)+'</form>';
if(type==="file")body='<form data-type="file"><div class="form-grid"><div class="field"><label>File name</label><input name="name" required value="'+esc(item?.name||"")+'"></div><div class="field"><label>Client</label><select name="client">'+cs+'</select></div><div class="field"><label>Status</label><select name="status"><option>Pending</option><option>Approved</option></select></div></div>'+actions(type)+'</form>';
content.innerHTML='<h2>'+(id?"Edit ":"Add ")+h+'</h2>'+body;back.hidden=false;back.style.display="grid";document.body.style.overflow="hidden";content.querySelectorAll("[data-close]").forEach(b=>b.onclick=close);content.querySelector("form").onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));let key=type==="event"?"events":type+"s";if(id){let x=state[key].find(x=>x.id==id);Object.keys(v).forEach(k=>{x[k]=k==="amount"||k==="progress"?+v[k]:v[k]})}else{let x={id:Date.now(),...v};if(type==="project")x.progress=+v.progress||0;if(type==="invoice")x.amount=+v.amount||0;if(type==="file"){x.type=(v.name.split(".").pop()||"FILE").toUpperCase();x.size=""}state[key].push(x)}save();close();setView(type==="event"?"calendar":type+"s")}}
function actions(type){return '<div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn primary">Save '+type+"</button></div>"}
function close(){back.hidden=true;back.style.display="none";document.body.style.overflow=""}
function remove(type,id){let key=type==="event"?"events":type+"s";state[key]=state[key].filter(x=>x.id!=id);save();setView(type==="event"?"calendar":type+"s")}
function bind(){page.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));page.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>modal(b.dataset.action));page.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>modal(b.dataset.edit,b.dataset.id));page.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{if(confirm("Delete this item?"))remove(b.dataset.remove,b.dataset.id)})}
const views={overview,clients,projects,calendar,invoices,files};
function setView(v){if(!views[v])return;document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));title.textContent=v[0].toUpperCase()+v.slice(1);views[v]();window.scrollTo(0,0)}
document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.getElementById("menuBtn").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
document.getElementById("notifyBtn").onclick=()=>alert("No new notifications.");
document.getElementById("profileBtn").onclick=()=>alert("Dillo workspace");
document.getElementById("modalClose").onclick=close;
back.onclick=e=>{if(e.target===back)close()};
document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});
setView("overview");
})();