(()=>{"use strict";
const KEY="dillo_dashboard_v3";
const data={
clients:[["Mia Santos","Bloom Wellness","Active"],["Lucas Reed","Northstar Finance","Active"],["Sofia Cruz","Casa Migration","Onboarding"],["Eli Parker","Good Energy Co.","Paused"]],
projects:[["Bloom — September Content","Bloom Wellness","In progress",72],["Northstar Brand Refresh","Northstar Finance","Review",88],["Casa TikTok Launch","Casa Migration","In progress",41]],
invoices:[["INV-104","Bloom Wellness","$650","Paid"],["INV-105","Northstar Finance","$900","Pending"],["INV-106","Casa Migration","$750","Overdue"]],
files:[["Bloom Brand Kit.pdf","Bloom Wellness","Approved"],["Northstar Logo Pack.zip","Northstar Finance","Pending"],["Casa Content Brief.docx","Casa Migration","Approved"]]
};
const page=document.getElementById("page"), title=document.getElementById("viewTitle");
const views={overview:overview,clients:clients,projects:projects,calendar:calendar,invoices:invoices,files:files};
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function shell(h,p){return '<div class="hero"><div><div class="eyebrow">DILLO SOCIALS</div><h1>'+h+'</h1><p>'+p+'</p></div></div>'}
function card(h,b){return '<section class="panel"><div class="panel-head"><h2>'+h+'</h2></div><div class="panel-body">'+b+'</div></section>'}
function table(headers,rows){return '<div style="overflow:auto"><table class="data-table"><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join("")+'</tr></thead><tbody>'+rows.join("")+'</tbody></table></div>'}
function overview(){page.innerHTML=shell("Good morning, Dillo. <span>Let’s make things move.</span>","Your Dillo HQ command center.");page.innerHTML+='<div class="kpis"><div class="kpi"><div class="kpi-top">Active clients</div><strong>2</strong><small>4 total relationships</small></div><div class="kpi"><div class="kpi-top">Projects in motion</div><strong>3</strong><small>2 currently active</small></div><div class="kpi"><div class="kpi-top">Paid this cycle</div><strong>$650</strong><small>Recorded payments</small></div><div class="kpi"><div class="kpi-top">Outstanding</div><strong>$1,650</strong><small>2 open invoices</small></div></div><div class="overview-grid"><div class="overview-main">'+card("Needs your attention",'<div class="list-row"><div><b>INV-106 is overdue</b><small>Casa Migration · $750</small></div><span class="tag red">Action needed</span></div><div class="list-row"><div><b>Northstar Logo Pack.zip needs approval</b><small>Northstar Finance</small></div><span class="tag yellow">Review</span></div>')+card("Projects at a glance",data.projects.map(p=>'<div class="list-row"><div><b>'+esc(p[0])+'</b><small>'+esc(p[1])+' · '+esc(p[2])+'</small></div><b>'+p[3]+'%</b></div>').join(""))+'</div><div class="overview-side">'+card("Coming up",'<div class="list-row"><div><b>Northstar review</b><small>September 20</small></div></div><div class="list-row"><div><b>Bloom strategy call</b><small>September 22</small></div></div><div class="list-row"><div><b>Bloom content due</b><small>September 24</small></div></div>')+card("Quick actions",'<div class="quick-grid"><button class="quick" data-view="clients"><strong>Clients</strong><span>Manage relationships</span></button><button class="quick" data-view="projects"><strong>Projects</strong><span>Track deliverables</span></button><button class="quick" data-view="invoices"><strong>Invoices</strong><span>Track payments</span></button><button class="quick" data-view="calendar"><strong>Calendar</strong><span>See upcoming work</span></button></div>')+'</div></div>'}
function clients(){page.innerHTML=shell("Your clients.","A simple home for every Dillo relationship.");page.innerHTML+=card("Client list",table(["Client","Business","Status"],data.clients.map(c=>'<tr><td><b>'+esc(c[0])+'</b></td><td>'+esc(c[1])+'</td><td>'+esc(c[2])+'</td></tr>')))}
function projects(){page.innerHTML=shell("Projects in motion.","Track the work Dillo is currently moving forward.");page.innerHTML+='<div class="project-grid">'+data.projects.map(p=>'<article class="project-card"><div class="project-top"><span class="tag blue">'+esc(p[2])+'</span><b>'+p[3]+'%</b></div><h3>'+esc(p[0])+'</h3><p>'+esc(p[1])+'</p><div class="progress"><i style="width:'+p[3]+'%"></i></div></article>').join("")+'</div>'}
function calendar(){page.innerHTML=shell("Calendar.","Calls, deadlines and launch moments.");page.innerHTML+=card("September 2026",'<div class="calendar-placeholder"><strong>September 18, 2026</strong><p>Upcoming: Northstar review · Sep 20<br>Bloom strategy call · Sep 22<br>Bloom content due · Sep 24<br>Casa launch · Sep 29</p></div>')}
function invoices(){page.innerHTML=shell("Invoices.","Keep billing visible and easy to follow.");page.innerHTML+=card("Invoice list",table(["Invoice","Client","Amount","Status"],data.invoices.map(i=>'<tr><td><b>'+esc(i[0])+'</b></td><td>'+esc(i[1])+'</td><td>'+esc(i[2])+'</td><td>'+esc(i[3])+'</td></tr>')))}
function files(){page.innerHTML=shell("Files.","A tidy home for client assets and deliverables.");page.innerHTML+=card("Shared files",table(["File","Client","Status"],data.files.map(f=>'<tr><td><b>'+esc(f[0])+'</b></td><td>'+esc(f[1])+'</td><td>'+esc(f[2])+'</td></tr>')))}
function setView(v){if(!views[v])return;document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));title.textContent=v.charAt(0).toUpperCase()+v.slice(1);try{views[v]();}catch(e){page.innerHTML=shell("Dillo HQ","This section is ready for content.");}window.scrollTo(0,0);if(window.innerWidth<=760)document.getElementById("sidebar").classList.remove("open");}
document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));
document.getElementById("menuBtn").addEventListener("click",()=>document.getElementById("sidebar").classList.toggle("open"));
document.getElementById("notifyBtn").addEventListener("click",()=>alert("You’re all caught up ✦"));
document.getElementById("profileBtn").addEventListener("click",()=>alert("Dillo workspace"));
document.getElementById("modalBackdrop").hidden=true;
setView("overview");
})();